server:
  port: 8060

spring:
  application:
    name: oauth2-server-msa-jdbc
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/msa_jdbc?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

  session:
    store-type: none

  #server:
#  session:
#    timeout: 600

  security:
    user:
      name: ivy
      password: aaaaaa

  main:
    allow-bean-definition-overriding: true

swagger:
  title: Security demo Application API
  description: Security demo API documentation
  version: 0.0.1
  defaultIncludePattern: /.*
  termsOfServiceUrl:
  contactName:
  contactUrl:
  contactEmail:
  license:
  licenseUrl:

demo:
  security:
    browser:
      loginType: REDIRECT
#      loginPage: /demo-signin.html

